# Generated by Django 4.2.4 on 2023-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='hhhv', upload_to='images'),
            preserve_default=False,
        ),
    ]
